package com.bradflaugher.aboutthataction.audio

import kotlin.math.pow

/**
 * Loudness trims (dB) per song, so every track the game plays sits in one tight loudness band
 * (BS.1770 integrated, at the default music volume, through the master bus). A song pinned to
 * one heat (title, themes, game over, sneak mixes) has one trim. A GUNS HOT arrangement has one
 * per point of [GRID] (calm, between, CAUTION, between, ALERT), followed linearly in between, so
 * the calm bed plays as full as the fight, the level climbs gently as heat builds, and a build
 * is density and brightness rather than a fader. A song with a trap drop
 * ([SongSpec.dropThreshold]) has three before the drop lands ([preDropGrid]: calm, halfway and
 * just under the threshold, so the bed holds its level as it builds) and three after it (the
 * upper half of [GRID]), so the drop arrives a step up, with its weight.
 *
 * GENERATED by `ATA_MUSIC_CALIBRATE=1 ./gradlew :app:testDebugUnitTest --tests '*MusicLevelsCalibration*'`
 * from renders of every song; rerun it after changing an arrangement, a patch or the mix.
 * [MusicQualityTest] fails when the music drifts out of the band.
 */
internal object MusicLevels {
    /** The heats a GUNS HOT arrangement's trims are measured at. */
    val GRID = floatArrayOf(0f, 0.25f, 0.5f, 0.75f, 0.95f)

    /** Where a drop song's first three trims are measured: calm, halfway, just under the drop. */
    fun preDropGrid(dropThreshold: Float) = floatArrayOf(0f, dropThreshold * 0.5f, dropThreshold - 0.02f)

    private val NONE = floatArrayOf(0f)

    fun of(name: String): FloatArray = overrides?.get(name) ?: TABLE[name] ?: NONE

    /** Trims to use instead of the table's (the calibration, between its passes). */
    @Volatile internal var overrides: Map<String, FloatArray>? = null

    /** Every song with a trim, for the calibration to start from. */
    internal val table: Map<String, FloatArray> get() = TABLE

    /**
     * The gain [trim] asks for at [heat]; for a drop song (six trims), [dropped] says whether its
     * drop has landed and [dropThreshold] where it lands. Allocation-free (the audio thread).
     */
    fun gainAt(trim: FloatArray, heat: Float, dropped: Boolean = true, dropThreshold: Float = -1f): Float {
        val h = heat.coerceIn(0f, 1f)
        val db = when (trim.size) {
            GRID.size -> along(trim, 0, GRID, 0, GRID.size, h)
            GRID.size + 1 -> if (dropped) {
                along(trim, 3, GRID, 2, 3, h)
            } else {
                // (Inline preDropGrid: no allocation.)
                val half = dropThreshold * 0.5f
                val top = dropThreshold - 0.02f
                if (h <= half) lerp(trim[0], trim[1], h / half) else lerp(trim[1], trim[2], (h - half) / (top - half))
            }
            else -> trim[0]
        }
        return 10f.pow(db / 20f)
    }

    /** Piecewise-linear [values] (from [vFrom]) over [count] points of [grid] (from [gFrom]), held flat past the ends. */
    private fun along(values: FloatArray, vFrom: Int, grid: FloatArray, gFrom: Int, count: Int, h: Float): Float {
        if (h <= grid[gFrom]) return values[vFrom]
        for (k in 1 until count) {
            val g0 = grid[gFrom + k - 1]
            val g1 = grid[gFrom + k]
            if (h <= g1) return lerp(values[vFrom + k - 1], values[vFrom + k], (h - g0) / (g1 - g0))
        }
        return values[vFrom + count - 1]
    }

    private fun lerp(a: Float, b: Float, t: Float) = a + (b - a) * t.coerceIn(0f, 1f)

    // @formatter:off
    private val TABLE: Map<String, FloatArray> = hashMapOf(
        // BEGIN GENERATED
        "title" to floatArrayOf(0.04f),
        "bull-theme" to floatArrayOf(-0.98f),
        "fox-theme" to floatArrayOf(1.67f),
        "hawk-theme" to floatArrayOf(-0.61f),
        "monkey-theme" to floatArrayOf(4.41f),
        "gameover" to floatArrayOf(-0.14f),
        "hell-bull" to floatArrayOf(3.96f, 3.87f, 1.77f, 0.61f, -0.03f, 0.07f),
        "hell-fox" to floatArrayOf(4.37f, 4.35f, 3.37f, 3.37f, 2.86f, 2.98f),
        "hell-hawk" to floatArrayOf(1.63f, 1.79f, 1.73f, 0.77f, 0.87f),
        "hell-monkey" to floatArrayOf(5.45f, 5.33f, 5.37f, 5.48f, 5.59f),
        "labs-bull" to floatArrayOf(3.33f, 2.94f, 0.59f, -1.18f, -1.64f, -1.54f),
        "labs-fox" to floatArrayOf(3.63f, 3.61f, 2.65f, 1.92f, 1.53f, 1.64f),
        "labs-hawk" to floatArrayOf(0.12f, 0.28f, 0.27f, -0.51f, -0.41f),
        "labs-monkey" to floatArrayOf(5.16f, 4.17f, 4.27f, 4.38f, 4.49f),
        "magma-bull" to floatArrayOf(4.15f, 3.93f, 1.65f, -0.01f, -0.59f, -0.49f),
        "magma-fox" to floatArrayOf(3.97f, 3.93f, 2.96f, 2.41f, 1.89f, 2.00f),
        "magma-hawk" to floatArrayOf(0.72f, 0.89f, 0.86f, -0.01f, 0.09f),
        "magma-monkey" to floatArrayOf(5.20f, 4.62f, 4.21f, 4.29f, 4.38f),
        "metro-bull" to floatArrayOf(3.13f, 2.86f, 0.76f, -0.64f, -1.21f, -1.11f),
        "metro-fox" to floatArrayOf(3.73f, 3.70f, 2.73f, 1.88f, 1.44f, 1.55f),
        "metro-hawk" to floatArrayOf(0.48f, 0.63f, 0.61f, -0.24f, -0.14f),
        "metro-monkey" to floatArrayOf(5.06f, 4.11f, 3.75f, 3.82f, 3.92f),
        "mines-bull" to floatArrayOf(4.49f, 4.23f, 1.64f, 0.46f, -0.20f, -0.11f),
        "mines-fox" to floatArrayOf(4.25f, 4.22f, 3.20f, 2.61f, 2.06f, 2.17f),
        "mines-hawk" to floatArrayOf(1.17f, 1.31f, 1.26f, 0.27f, 0.37f),
        "mines-monkey" to floatArrayOf(5.49f, 4.85f, 4.93f, 5.04f, 5.15f),
        "rooftop-bull" to floatArrayOf(3.28f, 3.05f, 0.74f, -1.79f, -2.33f, -2.23f),
        "rooftop-fox" to floatArrayOf(3.34f, 3.31f, 2.45f, 1.05f, 0.61f, 0.72f),
        "rooftop-hawk" to floatArrayOf(-0.59f, -0.42f, -0.40f, -1.15f, -1.05f),
        "rooftop-monkey" to floatArrayOf(4.35f, 3.14f, 3.16f, 3.27f, 3.38f),
        "tower-bull" to floatArrayOf(4.05f, 3.79f, 1.31f, -0.76f, -1.31f, -1.22f),
        "tower-fox" to floatArrayOf(4.01f, 3.98f, 3.05f, 1.94f, 1.47f, 1.59f),
        "tower-hawk" to floatArrayOf(0.01f, 0.17f, 0.19f, -0.66f, -0.56f),
        "tower-monkey" to floatArrayOf(5.41f, 4.25f, 4.23f, 4.34f, 4.46f),
        "void-bull" to floatArrayOf(3.49f, 3.18f, 1.28f, -0.56f, -1.15f, -1.05f),
        "void-fox" to floatArrayOf(3.91f, 3.88f, 3.11f, 2.12f, 1.67f, 1.78f),
        "void-hawk" to floatArrayOf(0.01f, 0.16f, 0.22f, -0.53f, -0.42f),
        "void-monkey" to floatArrayOf(4.94f, 4.00f, 4.00f, 4.11f, 4.21f),
        "hell-bull-sneak" to floatArrayOf(-2.00f),
        "hell-fox-sneak" to floatArrayOf(0.32f),
        "hell-hawk-sneak" to floatArrayOf(1.04f),
        "hell-monkey-sneak" to floatArrayOf(1.80f),
        "labs-bull-sneak" to floatArrayOf(-1.08f),
        "labs-fox-sneak" to floatArrayOf(0.22f),
        "labs-hawk-sneak" to floatArrayOf(0.79f),
        "labs-monkey-sneak" to floatArrayOf(1.50f),
        "magma-bull-sneak" to floatArrayOf(-1.41f),
        "magma-fox-sneak" to floatArrayOf(0.24f),
        "magma-hawk-sneak" to floatArrayOf(1.10f),
        "magma-monkey-sneak" to floatArrayOf(1.99f),
        "metro-bull-sneak" to floatArrayOf(-1.38f),
        "metro-fox-sneak" to floatArrayOf(0.25f),
        "metro-hawk-sneak" to floatArrayOf(0.95f),
        "metro-monkey-sneak" to floatArrayOf(1.48f),
        "mines-bull-sneak" to floatArrayOf(-0.95f),
        "mines-fox-sneak" to floatArrayOf(0.43f),
        "mines-hawk-sneak" to floatArrayOf(1.16f),
        "mines-monkey-sneak" to floatArrayOf(1.80f),
        "rooftop-bull-sneak" to floatArrayOf(-0.97f),
        "rooftop-fox-sneak" to floatArrayOf(0.33f),
        "rooftop-hawk-sneak" to floatArrayOf(1.15f),
        "rooftop-monkey-sneak" to floatArrayOf(0.99f),
        "tower-bull-sneak" to floatArrayOf(-0.94f),
        "tower-fox-sneak" to floatArrayOf(0.56f),
        "tower-hawk-sneak" to floatArrayOf(1.43f),
        "tower-monkey-sneak" to floatArrayOf(1.10f),
        "void-bull-sneak" to floatArrayOf(-1.36f),
        "void-fox-sneak" to floatArrayOf(1.13f),
        "void-hawk-sneak" to floatArrayOf(1.48f),
        "void-monkey-sneak" to floatArrayOf(1.93f),
        // END GENERATED
    )
    // @formatter:on
}
